function layoutElement(tag,css_class,parent){var element=document.createElement(tag);if(css_class!==null)element.className=css_class;parent.appendChild(element);return element;}
function layoutImage(img_array,css_class,parent){if(img_array===null)return;var img=document.createElement('img');if(css_class!==null)img.className=css_class;img.src=img_array['url'];img.alt=img_array['alt'];parent.appendChild(img);return img;}
function layoutHeading(heading,title,css_class,parent){if(title===null)return;var heading=document.createElement(heading);heading.innerHTML=title;if(css_class!==null)heading.className=css_class;parent.appendChild(heading);return heading;}
function layoutTitle(heading,title,icon,css_class,parent){if(title===null&&icon!==null)return layoutImage(icon,css_class,parent);if(title!==null&&icon===null)return layoutHeading(heading,title,css_class,parent);if(title===null&&icon===null)return;var div=document.createElement('div');if(css_class!==null)div.className=css_class;layoutHeading(heading,title,'',div);layoutImage(icon,'',div);parent.appendChild(div);return div;}
function layoutButton(link,heading,title,icon,css_class,parent,target=null,rel=null){if(link===null)return layoutTitle(heading,title,icon,css_class,parent);var a=document.createElement('a');if(css_class!==null)a.className=css_class;a.href=link['url'];a.title=link['title'];if(target!==null)a.target=target;if(rel!==null)a.rel=rel;if(title!==null)layoutHeading(heading,title,'',a);if(icon!==null)layoutImage(icon,'',a);parent.appendChild(a);return a;}
function layoutScript(url,parent){var script=document.createElement('script');script.src=url;parent.appendChild(script);}
function setGlobalVariables(){const url=document.location.origin+'/apostas/wp-content/themes/odds-scanner-main/ajax/update-wp-global-variables.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,wp_post_id:wp_post_id,},success:function(data){wp_site=data.wp_site
wp_post=data.wp_post},dataType:'json'});}
function setCookie(cname,cvalue,seconds){if(seconds){var d=new Date();d.setTime(d.getTime()+(seconds*1000));var expires='expires='+d.toUTCString();document.cookie=cname+'='+cvalue+';'+expires+';path=/';}
else document.cookie=cname+'='+cvalue+';path=/';}
function getCookie(cname){var name=cname+'=';var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1);if(c.indexOf(name)==0)return c.substring(name.length,c.length);}
return '';}
function checkCookie(new_identifier,time){var identifier=getCookie(new_identifier);if(identifier!='')return false;else if(new_identifier!=''&&new_identifier!=null){setCookie(new_identifier,new_identifier,time);return true;}}
function leftPad(num,size){num=num.toString();while(num.length<size)num='0'+num;return num;}
function accountSignOut(){var url=document.location.origin+'/apostas/wp-content/themes/odds-scanner-main/ajax/sign-out.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id},success:function(data){if(data.status=='success')location.replace(data.redirect.url);},dataType:'json'});}
function accountSignUp(form_id){var fields={};var fields_el=jQuery('#'+form_id+' .field input, #'+form_id+' .field textarea, #'+form_id+' .field select');for(var i=0;i<fields_el.length;i++)if(fields_el[i].name){var errors=jQuery(jQuery(fields_el[i]).parent().find('.error')[0]).children();for(var j=0;j<errors.length;j++)errors[j].remove();fields[fields_el[i].name]={name:fields_el[i].name,type:fields_el[i].type,required:fields_el[i].required,value:fields_el[i].value,checked:fields_el[i].checked};}
var url=document.location.origin+'/apostas/wp-content/themes/odds-scanner-main/ajax/sign-up.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,wp_post_id:wp_post_id,form_identifier:form_id,fields:fields},success:function(data){for(var i=0;i<fields_el.length;i++)if(fields_el[i].name)if(data.errors[fields_el[i].name]!=true){var error_el=jQuery(fields_el[i]).parent().find('.error')[0];for(var j=0;j<data.errors[fields_el[i].name].length;j++)layoutHeading('span',data.errors[fields_el[i].name][j],null,error_el);}
if(data.success==true){if(data.reload)location.reload();else location.replace(data.redirect.url);}},dataType:'json'});}
function accountSignIn(form_id){var fields={};var fields_el=jQuery('#'+form_id+' .field input, #'+form_id+' .field textarea, #'+form_id+' .field select');for(var i=0;i<fields_el.length;i++)if(fields_el[i].name){var errors=jQuery(jQuery(fields_el[i]).parent().find('.error')[0]).children();for(var j=0;j<errors.length;j++)errors[j].remove();fields[fields_el[i].name]={name:fields_el[i].name,type:fields_el[i].type,required:fields_el[i].required,value:fields_el[i].value,checked:fields_el[i].checked};}
var url=document.location.origin+'/apostas/wp-content/themes/odds-scanner-main/ajax/sign-in.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,wp_post_id:wp_post_id,form_identifier:form_id,fields:fields},success:function(data){for(var i=0;i<fields_el.length;i++)if(fields_el[i].name)if(data.errors[fields_el[i].name]!=true){var error_el=jQuery(fields_el[i]).parent().find('.error')[0];for(var j=0;j<data.errors[fields_el[i].name].length;j++)layoutHeading('span',data.errors[fields_el[i].name][j],null,error_el);}
if(data.success==true){if(data.reload)location.reload();else location.replace(data.redirect.url);}},dataType:'json'});}
function accountRecoverPassword(form_id){var fields={};var fields_el=jQuery('#'+form_id+' .field input, #'+form_id+' .field textarea, #'+form_id+' .field select');for(var i=0;i<fields_el.length;i++)if(fields_el[i].name){var errors=jQuery(jQuery(fields_el[i]).parent().find('.error')[0]).children();for(var j=0;j<errors.length;j++)errors[j].remove();fields[fields_el[i].name]={name:fields_el[i].name,type:fields_el[i].type,required:fields_el[i].required,value:fields_el[i].value,checked:fields_el[i].checked};}
var url=document.location.origin+'/apostas/wp-content/themes/odds-scanner-main/ajax/recover-password.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,form_identifier:form_id,fields:fields},success:function(data){for(var i=0;i<fields_el.length;i++)if(fields_el[i].name)if(data.errors[fields_el[i].name]!=true){var error_el=jQuery(fields_el[i]).parent().find('.error')[0];for(var j=0;j<data.errors[fields_el[i].name].length;j++)layoutHeading('span',data.errors[fields_el[i].name][j],null,error_el);}
if(data.success==true){var success_message=jQuery('#'+form_id+' > form > .success')[0];var success_messages=jQuery(success_message).children();for(var j=0;j<success_messages.length;j++)success_messages[j].remove();layoutHeading('span',data.success_message,null,success_message);}},dataType:'json'});}
function accountChangePassword(form_id){var fields={};var fields_el=jQuery('#'+form_id+' .field input, #'+form_id+' .field textarea, #'+form_id+' .field select');for(var i=0;i<fields_el.length;i++)if(fields_el[i].name){var errors=jQuery(jQuery(fields_el[i]).parent().find('.error')[0]).children();for(var j=0;j<errors.length;j++)errors[j].remove();fields[fields_el[i].name]={name:fields_el[i].name,type:fields_el[i].type,required:fields_el[i].required,value:fields_el[i].value,checked:fields_el[i].checked};}
var url=document.location.origin+'/apostas/wp-content/themes/odds-scanner-main/ajax/change-password.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,wp_post_id:wp_post_id,form_identifier:form_id,fields:fields},success:function(data){for(var i=0;i<fields_el.length;i++)if(fields_el[i].name)if(data.errors[fields_el[i].name]!=true){var error_el=jQuery(fields_el[i]).parent().find('.error')[0];for(var j=0;j<data.errors[fields_el[i].name].length;j++)layoutHeading('span',data.errors[fields_el[i].name][j],null,error_el);}
if(data.success==true){var success_message=jQuery('#'+form_id+' > form > .success')[0];var success_messages=jQuery(success_message).children();for(var j=0;j<success_messages.length;j++)success_messages[j].remove();layoutHeading('span',data.success_message,null,success_message);}},dataType:'json'});}
function wpPostsViews(wp_post_id){if(checkCookie('wp-posts-views-'+wp_post_id)){var url=document.location.origin+'/apostas/wp-content/themes/odds-scanner-main/ajax/wp-posts-views.php';jQuery.ajax({url:url,data:{wp_post_id:wp_post_id},success:function(data){},dataType:'json'});}}
function setCowntdown(){setInterval(function(){jQuery('.countdown').each(function(){var seconds=jQuery(this).find('.seconds > span');if(seconds[0].innerHTML==0){seconds[0].innerHTML=59;var minutes=jQuery(this).find('.minutes > span');if(minutes[0].innerHTML==0){minutes[0].innerHTML=59;var hours=jQuery(this).find('.hours > span');if(hours[0].innerHTML==0){hours[0].innerHTML=23;var days=jQuery(this).find('.days > span');days[0].innerHTML=leftPad(days[0].innerHTML-1,2);}
else hours[0].innerHTML=leftPad(hours[0].innerHTML-1,2);}
else minutes[0].innerHTML=leftPad(minutes[0].innerHTML-1,2);}
else seconds[0].innerHTML=leftPad(seconds[0].innerHTML-1,2);});},1000);}
function smoothHref(){jQuery('[href*="#"]').click(function(e){e.preventDefault();var url=this.href;var url_array=url.split('#');if(url_array[1]!=''){var fixed_header=jQuery('header');var fixed_header_height=fixed_header.length>0?fixed_header[0].offsetHeight:0;var widget_navigation=window.innerWidth<=1199?jQuery('.widget-navigation ul')[0].offsetHeight:0;jQuery('html, body').animate({scrollTop:jQuery(jQuery('#'+url_array[url_array.length-1]).offset().top)[0]-fixed_header_height-widget_navigation-5},500);}});}
function handleFixedNavigationWidget(){var header=jQuery('header');var hero=jQuery('.hero');var sidebar=jQuery('.right-sidebar');if(window.innerWidth>=1200){jQuery(window).scroll(function(){var scroll=jQuery(window).scrollTop();var sidebar_height=sidebar.length>0?jQuery(sidebar[0]).parent().outerHeight(true):0;var header_height=header.length>0?header[0].offsetHeight:0;var hero_height=hero.length>0?hero[0].offsetHeight:0;var widgets_height=0;var widgets=sidebar.find('.widget:not(.widget-navigation)');for(var i=0;i<widgets.length;i++)widgets_height+=jQuery(widgets[i]).outerHeight(true)-40;var fixed_widget_height=0;var fixed_widget=sidebar.find('.widget > .navigation');fixed_widget_height+=jQuery(fixed_widget[0]).parent().outerHeight(true);if(fixed_widget){if(scroll>header_height+hero_height+widgets_height){if(scroll+fixed_widget_height>sidebar_height+header_height+40){if(!jQuery(fixed_widget[0]).parent().hasClass('fixed-bottom')){jQuery(fixed_widget[0]).parent()[0].style.top=sidebar_height-fixed_widget_height-40+'px';jQuery(fixed_widget[0]).parent().addClass('fixed-bottom');}}
else{jQuery(fixed_widget[0]).parent().addClass('fixed');jQuery(fixed_widget[0]).parent().removeClass('fixed-bottom');jQuery(fixed_widget[0]).parent()[0].style.top=header_height+'px';}}
else{jQuery(fixed_widget[0]).parent().removeClass('fixed');jQuery(fixed_widget[0]).parent()[0].style.top=0;}}});}}
function responsivenessDisplayNavigationWidget(){if(window.innerWidth<=1199){jQuery(window).scroll(function(){var scroll=jQuery(window).scrollTop();if(scroll>320)jQuery('.widget-navigation').addClass('show');else jQuery('.widget-navigation').removeClass('show');});}}
function toggleFaq(element){var current_faq_card=jQuery(element).parent();var content_block=current_faq_card.parent();var faq_cards=content_block[0].children;for(var i=0;i<faq_cards.length;i++){if(faq_cards[i]==current_faq_card[0]){current_faq_card.toggleClass('open');current_faq_card.toggleClass('close');}
else{jQuery(faq_cards[i]).removeClass('open');jQuery(faq_cards[i]).addClass('close');}}}
function showAll(element){var cards=jQuery(element).parent()[0].children;for(var i=0;i<cards.length;i++)jQuery(cards[i]).removeClass('hide');element.remove();}
function shoreMoreLessContent(element,strings){var title=jQuery(element).find('span');var more_content=jQuery(element).parent().find('.more-content');if(element.className.includes('less')){jQuery(element).removeClass('less');more_content.removeClass('less');title[0].innerHTML=strings['less']['title'];}
else{jQuery(element).addClass('less');more_content.addClass('less');title[0].innerHTML=strings['more']['title'];}}
function openSubmenu(element){jQuery(element).parent().parent().toggleClass('opened');}
function changeGeoTarget(geographical_area_id){var url=document.location.origin+'/apostas/wp-content/themes/odds-scanner-main/ajax/geo-target-change.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,wp_user_id:wp_user_id,geographical_area_id:geographical_area_id},success:function(data){location.reload();},dataType:'json'});}
window.addEventListener('load',function(){onLoad();});function onLoad(){wpPostsViews(wp_post_id);setCowntdown();smoothHref();const body=jQuery('body');if(body.hasClass('sportsbook'))if(window.innerWidth<575)handleSportsbookReviewHeroStructure();bannerManager();responsivenessDisplayNavigationWidget();handleFixedNavigationWidget();last_width=window.innerWidth;dropCookie();}
function handleSearchOnClick(element){const currentElement=jQuery(element);const searchBarElement=currentElement.closest('.search');const inputElement=searchBarElement.find('input');var url=document.location.origin+'/apostas/wp-content/themes/os-sportsbook-child/ajax/search.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,},success:function(data){if(inputElement.val())location.href=`${data.link.url}?search=${inputElement.val()}`;},dataType:'json'});}
function handleSearchBarInputOnKeyDown(event){const currentElement=jQuery(event.currentTarget);const searchBarElement=currentElement.closest('.search');const inputElement=searchBarElement.find('input');var url=document.location.origin+'/apostas/wp-content/themes/os-sportsbook-child/ajax/search.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,},success:function(data){if(event.key=='Enter'&&inputElement.val())location.href=`${data.link.url}?search=${inputElement.val()}`;},dataType:'json'});}
function handleNotRecommendedPopUpCloseOnClick(element){const currentElement=jQuery(element);currentElement.closest('.not-recommended-pop-up').remove();}
function handleFooterCTACloseOnClick(element){const currentElement=jQuery(element);currentElement.closest('.bottom-cta').remove();}
function handleShowMoreCardsOnClick(element){const currentElement=jQuery(element);const cardsContainerElement=currentElement.parent();cardsContainerElement.children().each(function(){if($(this).hasClass('hide'))$(this).removeClass('hide');});currentElement.remove();}
function handleMobileMenuOpenCloseOnClick(){const body=jQuery('body');const bodyElement=body[0];const mobileMenuNavigation=jQuery('.menu-navigation.responsiveness');const mobileMenuNavigationElement=mobileMenuNavigation[0];const primaryMenu=jQuery('.primary-menu.responsiveness');mobileMenuNavigation.children().each(function(){if($(this).hasClass('hide'))$(this).removeClass('hide');else $(this).addClass('hide');});if(mobileMenuNavigationElement.className.includes('closed')){mobileMenuNavigation.toggleClass('closed');primaryMenu.toggleClass('closed');body.toggleClass('responsiveness-menu-open');}
else{mobileMenuNavigation.toggleClass('closed');primaryMenu.toggleClass('closed');body.toggleClass('responsiveness-menu-open');}}
function handleSportsbookTablesActiveOnClick(element){const headElement=jQuery(element).parent();let headElements;if(headElement)headElements=headElement.children();const bodyElement=jQuery(element).parent().parent().find('.body');let bodyElements;if(bodyElement)bodyElements=bodyElement.children();for(var i=0;i<bodyElements.length;i++){if(bodyElements[i].className==element.className||(bodyElements[i].className).includes(element.className))jQuery(bodyElements[i]).addClass('active');else jQuery(bodyElements[i]).removeClass('active');};for(var i=0;i<headElements.length;i++){if(headElements[i].className==element.className||(headElements[i].className).includes(element.className))jQuery(headElements[i]).addClass('active');else jQuery(headElements[i]).removeClass('active');};};function handleSportsbookReviewHeroStructure(){const verticalCard=jQuery('main .hero .row .vertical');const verticalCardElement=verticalCard[0];const heroRow=jQuery('main .hero .row .col-xl-8');const heroRowElement=heroRow[0];const heroContent=jQuery('main .hero .row .content');const heroContentElement=heroContent[0];const cardColumn=jQuery('main .hero .row .col-xl-4');const cardColumnElement=cardColumn[0];if(window.innerWidth<575){heroRowElement.insertBefore(verticalCardElement,heroContentElement);}
else{cardColumnElement.appendChild(verticalCardElement);}}
let banners_map=[];function bannerManager(){const widgetAreas=jQuery('.banner-manager');widgetAreas.each(function(){const bannerManagerContainer=$(this);const dataId=$(this).attr('data-id');const url=document.location.origin+'/apostas/wp-content/themes/os-sportsbook-child/ajax/banner-manager.php';jQuery.ajax({url:url,data:{data_id:dataId,wp_site_id:wp_site_id,wp_post_id:wp_post_id},success:function(bannerObject){if(bannerObject&&bannerObject['wp_fields']['banners_banners'])for(const[key,banner]of Object.entries(bannerObject['wp_fields']['banners_banners'])){if(getCookie('banner_close_'+dataId)!='')break;banners_map[dataId]=0;if(getCookie('banner_index_'+dataId)!='')banners_map[dataId]=getCookie('banner_index_'+dataId);if(key!=banners_map[dataId])continue;if(banner['style']){const bannerContainer=document.createElement('div');bannerContainer.classList.add('banner');bannerContainer.setAttribute("data-os_element",'Footer');if(banner['advertiser_geographical_area']['identifier']!==null)bannerContainer.setAttribute('data-os_adv_id',banner['advertiser_geographical_area']['identifier']);if(banner['advertiser_geographical_area']['marketing_source_identifier']!==null)bannerContainer.setAttribute('data-os_ms',banner['advertiser_geographical_area']['marketing_source_identifier']);if(bannerObject['wp_fields']['navigation_close_icon']){const closeDiv=document.createElement('div');closeDiv.classList.add('close');closeDiv.setAttribute('onclick','handleCloseBannerOnClick(this);');const navigationCloseImg=document.createElement('img');if(bannerObject['wp_fields']['navigation_close_icon']['width'])navigationCloseImg.setAttribute('width',bannerObject['wp_fields']['navigation_close_icon']['width']);if(bannerObject['wp_fields']['navigation_close_icon']['height'])navigationCloseImg.setAttribute('height',bannerObject['wp_fields']['navigation_close_icon']['height']);if(bannerObject['wp_fields']['navigation_close_icon']['url'])navigationCloseImg.setAttribute('src',bannerObject['wp_fields']['navigation_close_icon']['url']);if(bannerObject['wp_fields']['navigation_close_icon']['alt'])navigationCloseImg.setAttribute('alt',bannerObject['wp_fields']['navigation_close_icon']['alt']);$(closeDiv).append(navigationCloseImg);$(bannerContainer).append(closeDiv);}
for(const[key,style]of Object.entries(banner['style'])){const bannerSizeElement=document.createElement('div');bannerSizeElement.classList.add('banner-size');bannerSizeElement.classList.add(key);const buttonContainer=document.createElement('a');if(banner['advertiser_geographical_area']['donation_link']['url'])buttonContainer.setAttribute('href',banner['advertiser_geographical_area']['donation_link']['url']);if(banner['advertiser_geographical_area']['donation_link']['title'])buttonContainer.setAttribute('title',banner['advertiser_geographical_area']['donation_link']['title']);if(banner['advertiser_geographical_area']['donation_link']['title'])jQuery(buttonContainer).addClass('os-ms');if(banner['advertiser_geographical_area']['donation_link']['title'])buttonContainer.setAttribute('data-os_aga',banner['advertiser_geographical_area']['donation_link']['title']);buttonContainer.setAttribute('data-os_dlp',banner['placement']);buttonContainer.setAttribute('data-os_dlt','Image');buttonContainer.setAttribute('target','_blank');buttonContainer.setAttribute('rel','nofollow');const bannerImage=document.createElement('img');if(style['width'])bannerImage.setAttribute('width',style['width']);if(style['height'])bannerImage.setAttribute('height',style['height']);if(style['url'])bannerImage.setAttribute('src',style['url']);if(style['alt'])bannerImage.setAttribute('alt',style['alt']);buttonContainer.appendChild(bannerImage);bannerSizeElement.appendChild(buttonContainer);bannerContainer.appendChild(bannerSizeElement);}
$(bannerManagerContainer).append(bannerContainer);banners_map[dataId]++;if(banners_map[dataId]>Object.keys(bannerObject['wp_fields']['banners_banners']).length-1)banners_map[dataId]=0;setCookie('banner_index_'+dataId,banners_map[dataId]);return;}};},dataType:'json'});});}
function handleCloseBannerOnClick(element){const currentElement=jQuery(element);const bannerManager=currentElement.closest('.banner-manager');const bannerElement=currentElement.closest('.banner');setCookie('banner_close_'+bannerManager.attr('data-id'),'1');bannerElement.remove();}
let last_width=0;window.addEventListener('resize',()=>{if(window.innerWidth<1200&&last_width>1200)handleMobileMenuStructure();else if(window.innerWidth>=1200&&last_width<=1200)handleMobileMenuStructure();const body=jQuery('body');if(body.hasClass('sportsbook')){if(window.innerWidth<575&&last_width>575)handleSportsbookReviewHeroStructure();else if(window.innerWidth>=575&&last_width<=575)handleSportsbookReviewHeroStructure();}
last_width=window.innerWidth;});function requestSinglePostNavigation(){const url=document.location.origin+'/apostas/wp-content/themes/os-sportsbook-child/ajax/single-post-navigation.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,data:filters},success:function(articles_wp_posts){layoutSinglePostNavigation(articles_wp_posts);},dataType:'json'});}
function layoutSinglePostNavigation(articles_wp_posts){const articlesBody=jQuery('.articles.grid');const articlesBodyElement=articlesBody[0];articlesBody.empty();var counter=0;if(articles_wp_posts['articles_wp_posts'])for(const[key,article_wp_post]of Object.entries(articles_wp_posts['articles_wp_posts'])){if(filters['author']){if(filters['author']==article_wp_post['wp_author']['id']){if(counter>=filters['pagination']['page']&&counter<=(filters['pagination']['page']+filters['pagination']['offset']-1))layoutWpPostsNavigationRow(article_wp_post);counter++;}
else continue;}
else{if(counter>=filters['pagination']['page']&&counter<=(filters['pagination']['page']+filters['pagination']['offset']-1))layoutWpPostsNavigationRow(article_wp_post);counter++;}}
let total_pages;if(parseInt(counter)>filters['pagination']['offset'])total_pages=Math.ceil(parseInt(counter)/filters['pagination']['offset']);else total_pages=1;const current_page=Math.ceil(filters['pagination']['page']/filters['pagination']['offset'])+1;const paginationDiv=jQuery('.pagination');const paginationDivElement=paginationDiv[0];const navigationIconImg=articles_wp_posts['navigation_icon'];paginationDiv.empty();layoutDatabasePagination(total_pages,current_page,navigationIconImg,paginationDivElement);}
function requestFreeGameNavigation(){const url=document.location.origin+'/apostas/wp-content/themes/os-sportsbook-child/ajax/free-game-navigation.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,data:filters},success:function(articles_wp_posts){layoutSinglePostNavigation(articles_wp_posts);},dataType:'json'});}
function requestBettingTipsNavigation(){const url=document.location.origin+'/apostas/wp-content/themes/os-sportsbook-child/ajax/betting-tips-navigation.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,data:filters},success:function(articles_wp_posts){layoutBettingTipsNavigation(articles_wp_posts);},dataType:'json'});}
function layoutBettingTipsNavigation(articles_wp_posts){const articlesBody=jQuery('.articles.grid');const articlesBodyElement=articlesBody[0];articlesBody.empty();var counter=0;if(articles_wp_posts['articles_wp_posts'])for(const[key,article_wp_post]of Object.entries(articles_wp_posts['articles_wp_posts'])){let validate=true;if(filters['author']){if(filters['author']!=article_wp_post['wp_author']['id'])validate=false;}
if(filters['parent']){if(filters['parent']!=article_wp_post['parent'])validate=false;}
if(validate){if(counter>=filters['pagination']['page']&&counter<=(filters['pagination']['page']+filters['pagination']['offset']-1))layoutWpPostsNavigationRow(article_wp_post);counter++;}
else continue;}
let total_pages;if(parseInt(counter)>filters['pagination']['offset'])total_pages=Math.ceil(parseInt(counter)/filters['pagination']['offset']);else total_pages=1;const current_page=Math.ceil(filters['pagination']['page']/filters['pagination']['offset'])+1;const paginationDiv=jQuery('.pagination');const paginationDivElement=paginationDiv[0];const navigationIconImg=articles_wp_posts['navigation_icon'];paginationDiv.empty();layoutDatabasePagination(total_pages,current_page,navigationIconImg,paginationDivElement);}
function requestWpPostsNavigation(){const url=document.location.origin+'/apostas/wp-content/themes/os-sportsbook-child/ajax/wp-posts-navigation.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,data:filters},success:function(articles_wp_posts){layoutWpPostsNavigation(articles_wp_posts);},dataType:'json'});}
function layoutWpPostsNavigation(articles_wp_posts){const articlesBody=jQuery('.articles.grid');const articlesBodyElement=articlesBody[0];articlesBody.empty();var counter=0;if(articles_wp_posts['articles_wp_posts'])for(const[key,article_wp_post]of Object.entries(articles_wp_posts['articles_wp_posts'])){if(filters['author']){if(filters['author']==article_wp_post['wp_author']['id']){if(counter>=filters['pagination']['page']&&counter<=(filters['pagination']['page']+filters['pagination']['offset']-1))layoutWpPostsNavigationRow(article_wp_post);counter++;}
else continue;}
else{if(counter>=filters['pagination']['page']&&counter<=(filters['pagination']['page']+filters['pagination']['offset']-1))layoutWpPostsNavigationRow(article_wp_post);counter++;}}
let total_pages;if(parseInt(counter)>filters['pagination']['offset'])total_pages=Math.ceil(parseInt(counter)/filters['pagination']['offset']);else total_pages=1;const current_page=Math.ceil(filters['pagination']['page']/filters['pagination']['offset'])+1;const paginationDiv=jQuery('.pagination');const paginationDivElement=paginationDiv[0];const navigationIconImg=articles_wp_posts['navigation_icon'];paginationDiv.empty();layoutDatabasePagination(total_pages,current_page,navigationIconImg,paginationDivElement);}
function layoutWpPostsNavigationRow(article_wp_post){const articlesBody=jQuery('.articles.grid');const articlesBodyElement=articlesBody[0];const articlesRow=layoutElement('div','wp-post vertical medium-card',articlesBodyElement);if(article_wp_post['url'])layoutButton({url:article_wp_post['url'],title:article_wp_post['name']},null,null,null,'area-link',articlesRow);const topData=layoutElement('div','top',articlesRow);const featuredImageData=layoutElement('div','featured-image',topData);$(featuredImageData).css('background-image',`url(${article_wp_post['featured_image']['url']})`);const bottomData=layoutElement('div','bottom',articlesRow);const titleData=layoutElement('div','title',bottomData);const title=layoutButton({url:article_wp_post['url'],title:article_wp_post['name']},'span',article_wp_post['name'],null,null,titleData);const excerptData=layoutElement('div','excerpt',bottomData);$(excerptData).text(article_wp_post['wp_fields']['wp_excerpt']);const metaData=layoutElement('div','meta',articlesRow);const authorData=layoutElement('div','author',metaData);const authorPrefix=layoutHeading('span',article_wp_post['author_meta_prefix'],'prefix',authorData);if(article_wp_post['wp_author']['review'])layoutButton({url:article_wp_post['wp_author']['review']['url'],title:article_wp_post['wp_author']['review']['name']},'span',article_wp_post['wp_author']['review']['name'],null,null,authorData);else layoutHeading('span',article_wp_post['wp_author']['display_name'],'name',authorData);const publishedDateDate=layoutElement('div','published-date',metaData);const publishedDate=layoutButton({url:article_wp_post['url'],title:article_wp_post['name']},'span',article_wp_post['published_date'],article_wp_post['published_date_icon'],null,publishedDateDate);}
function handleDatabasePaginationNavigation(element){const navigation=jQuery(element);const direction=navigation.attr('data-navigation');const current_page=Math.ceil(filters['pagination']['page']/filters['pagination']['offset'])+1;if(direction=='1')filters['pagination']['page']=current_page*filters['pagination']['offset'];else if(direction=='-1')filters['pagination']['page']=((current_page-2)>=0?current_page-2:0)*filters['pagination']['offset'];if(filters['category']){if(filters['category']=='betting_tip')requestBettingTipsNavigation();if(filters['category']=='post')requestSinglePostNavigation();if(filters['category']=='free_game')requestFreeGameNavigation();}
else requestWpPostsNavigation();}
function handleDatabasePaginationPage(element){const pageNumberElement=jQuery(element);const pageNumber=pageNumberElement.attr('data-page');filters['pagination']['page']=(parseInt(pageNumber)-1)*filters['pagination']['offset'];if(filters['category']){if(filters['category']=='betting_tip')requestBettingTipsNavigation();if(filters['category']=='post')requestSinglePostNavigation();if(filters['category']=='free_game')requestFreeGameNavigation();}
else requestWpPostsNavigation();}
function layoutDatabasePagination(total_pages,current_page,icon,parent){if(current_page===null)return;if(current_page>1){const navigationLeft=layoutElement('div','navigation left',parent);layoutImage(icon,null,navigationLeft);const navigationLeftElement=jQuery(navigationLeft);navigationLeftElement.attr('data-navigation','-1');navigationLeftElement.on('click',function(event){event.stopPropagation();event.bubbles=false;handleDatabasePaginationNavigation($(this));});}
const pagesDiv=layoutElement('div','pages',parent);if(current_page>1){const pageNumber=layoutElement('div','page number',pagesDiv);layoutHeading('span','1',null,pageNumber);const pageNumberElement=jQuery(pageNumber);pageNumberElement.attr('data-page','1');pageNumberElement.on('click',function(event){event.stopPropagation();event.bubbles=false;handleDatabasePaginationPage($(this));});}
if(current_page-2>2){const pageDots=layoutElement('div','page dots',pagesDiv);layoutHeading('span','...',null,pageDots);}
if(current_page-2>1){const pageNumber=layoutElement('div','page number',pagesDiv);layoutHeading('span',current_page-2,null,pageNumber);const pageNumberElement=jQuery(pageNumber);pageNumberElement.attr('data-page',current_page-2);pageNumberElement.on('click',function(event){event.stopPropagation();event.bubbles=false;handleDatabasePaginationPage($(this));});}
if(current_page-1>1){const pageNumber=layoutElement('div','page number',pagesDiv);layoutHeading('span',current_page-1,null,pageNumber);const pageNumberElement=jQuery(pageNumber);pageNumberElement.attr('data-page',current_page-1);pageNumberElement.on('click',function(event){event.stopPropagation();event.bubbles=false;handleDatabasePaginationPage($(this));});}
const pageNumberCurrent=layoutElement('div','page number current',pagesDiv);layoutHeading('span',current_page,null,pageNumberCurrent);const pageNumberCurrentElement=jQuery(pageNumberCurrent);pageNumberCurrentElement.attr('data-page',current_page);pageNumberCurrentElement.on('click',function(event){event.stopPropagation();event.bubbles=false;handleDatabasePaginationPage($(this));});if(current_page+1<total_pages){const pageNumber=layoutElement('div','page number',pagesDiv);layoutHeading('span',current_page+1,null,pageNumber);const pageNumberElement=jQuery(pageNumber);pageNumberElement.attr('data-page',current_page+1);pageNumberElement.on('click',function(event){event.stopPropagation();event.bubbles=false;handleDatabasePaginationPage($(this));});}
if(current_page+2<total_pages){const pageNumber=layoutElement('div','page number',pagesDiv);layoutHeading('span',current_page+2,null,pageNumber);const pageNumberElement=jQuery(pageNumber);pageNumberElement.attr('data-page',current_page+2);pageNumberElement.on('click',function(event){event.stopPropagation();event.bubbles=false;handleDatabasePaginationPage($(this));});}
if(current_page+2<total_pages-1){const pageDots=layoutElement('div','page dots',pagesDiv);layoutHeading('span','...',null,pageDots);}
if(current_page<total_pages){const pageNumber=layoutElement('div','page number',pagesDiv);layoutHeading('span',total_pages,null,pageNumber);const pageNumberElement=jQuery(pageNumber);pageNumberElement.attr('data-page',total_pages);pageNumberElement.on('click',function(event){event.stopPropagation();event.bubbles=false;handleDatabasePaginationPage($(this));});const navigationRight=layoutElement('div','navigation right',parent);layoutImage(icon,null,navigationRight);const navigationRightElement=jQuery(navigationRight);navigationRightElement.attr('data-navigation','1')
navigationRightElement.on('click',function(event){event.stopPropagation();event.bubbles=false;handleDatabasePaginationNavigation($(this));});}}
function dropCookie(){const url=document.location.origin+'/apostas/wp-content/themes/os-sportsbook-child/ajax/drop-cookie.php';jQuery.ajax({url:url,data:{wp_site_id:wp_site_id,wp_post_id:wp_post_id},success:function(data){data.advertisers_geographical_areas.forEach(advertiserGeographicalArea=>{const bodyDiv=jQuery(document.body)[0];const iframe=layoutElement('iframe',null,bodyDiv);iframe.src=advertiserGeographicalArea.donation_link.url;iframe.style.display='none';jQuery(iframe).addClass('os-ms');iframe.setAttribute("data-os_element",'Main');if(advertiserGeographicalArea.identifier!==null)iframe.setAttribute("data-os_adv_id",advertiserGeographicalArea.identifier);if(advertiserGeographicalArea.marketing_source_identifier!==null)iframe.setAttribute("data-os_ms",advertiserGeographicalArea.marketing_source_identifier);})},dataType:'json'});}
function copyToClipboard(element,copyURL){const currentElement=jQuery(element);currentElement.parent().children().each(function(){jQuery(this).toggleClass('active');});if(!copyURL)navigator.clipboard.writeText(window.location.href);else{navigator.clipboard.writeText(copyURL);setTimeout(()=>{currentElement.parent().children().each(function(){jQuery(this).toggleClass('active');});},2*1000);}}